// Aimee Denyse Niwenshuti
// CSE 2 Homework 07
// Write a program that forces the user to enter an integer between 1 and 9
// inclusive, and then prints out displays that depend on the value entered
// using multiple methods
// November 4th, 2014

import java.util.Scanner;

public class BlockedAgain{
    public static void main(String [] args){
  
        //force user to enter int in range 1-9, inclusive.
        int m = getInt(); 
        
        allBlocks(m);
    }
    

public static int getInt(){        //continues to request the input from the user 
    
    boolean result= true;
    int number=0;
    while (result){
        number=checkInt();
        result=checkRange(number);
    }
    
    return number;    
    }
    

public static int checkInt(){  //accept the input and test whether it is an integer 
    Scanner input=  new Scanner( System.in );  //declare an instance of the Scanner object
     
    System.out.print("Enter an integer between 1 and 9: ");
    while (!input.hasNextInt()){
        System.out.println("You did not enter an int, try again");
        input.next();
    }
    int e=input.nextInt();
    return e;
    
    
}

public static boolean checkRange(int i){ //accept the input and test whether it is within range 1-9
  
    
    if (i>9 || i<1){
        
        System.out.println("The interger should be between 1 and 9, try again: ");
        return true;
    }
    else{
        return false;
    }
}

public static void allBlocks(int x){ // accept the input generated by getInt()
    block(x);
}

public static void block(int x){ // accept input from allblocks and print each individual block
    int numberOfLines=1;
        
    int digitsInOneLine=1;
        
    int count=0;
        
    int numberOfDash=0;
    
    int inputValue=1;
    
    int i=x;
        while (inputValue<=i){
            line(numberOfLines, digitsInOneLine, numberOfDash, count, inputValue);
            numberOfLines=1;
            
            inputValue++;
        }
    
}

// accept input from block() and generate each line and indent distances

public static void line(int numberOfLines, int digitsInOneLine, int numberOfDash, int count, int inputValue){
    
    int space=0;
    while (numberOfLines<=inputValue) {
                    digitsInOneLine=(inputValue*2)-1;
                    
                    while(space<(9-inputValue)){
                        System.out.print("   ");
                        space++;
                        
                    }
                    space=0;
                    while (count<digitsInOneLine) {
                       System.out.print(" "+inputValue+" " );
                       count++;
                    }
                count=0;
                System.out.println();
                numberOfLines++;   
                }
                
                while(space<(9-inputValue)){
                        System.out.print("   ");
                        space++;
                        
                    }
                    space=0;
    while(numberOfDash<digitsInOneLine) {
        
                System.out.print( " _ " );
                numberOfDash++;
            }
            System.out.println();
            numberOfDash=0;
            System.out.println();
    
}


}